If condalock doesn't exist and you are reading the lock file, install it first, so you can use the lock file, remove some of the verbosity

diff --git a/py_env_create b/py_env_create
--- a/py_env_create
+++ b/py_env_create
@@ -117,15 +117,32 @@ if [ "$readlock" == "Yes" ]; then
    conda-lock --help >& /dev/null
    error=$?
    if [ $error != 0 ]; then
+      # conda init bash may be required to activate the environemnt
       conda init bash
       cmd="conda activate $condalockenv"
       echo $cmd
       $cmd
       if [ $? != 0 ]; then
-          echo "Trouble activating the $condalockenv python environment"
-          echo "You need to have run this script before so that the environment is setup"
-          exit -2
+          echo "WARNING: Trouble activating the $condalockenv python environment"
+          echo "         In general you need to have run this script before so that the environment is setup"
+          echo "We will attempt to install now..."
+          cmd="conda install --yes --quiet --mkdir --channel conda-forge --name $condalockenv --file $condadir/$condalockenvfile"
+          echo "$cmd"
+          $cmd
+          if [ $? != 0 ]; then
+             echo "Trouble setting up $condalockenv"
+             exit -1
+          fi
+          cmd="conda activate $condalockenv"
+          echo $cmd
+          $cmd
+          if [ $? != 0 ]; then
+             echo "Trouble activating $condalockenv"
+             exit -1
+          fi
       fi
+      cmd="conda deactivate"
+      $cmd
    fi
    condafilepath="$condadir/$lockfile"
    if [ ! -f $condafilepath ]; then
@@ -166,19 +183,27 @@ fi
 # Install the environemnt
 #
 echo "Install $ctsm_python this can take a long time, be patient...."
+if [ "$readlock" != "Yes" ]; then
+    echo "    If this seems to be hanging (taking hours) or it aborts with an error -- retry using the --read-lock option"
+fi
+echo "    ...."
+echo "    ...."
+echo "    ...."
 verbosity="--quiet"
+loglevel="ERROR"
 if [ "$verbose" == "Yes" ]; then
   verbosity="--verbose"
+  loglevel="INFO"
 fi
 if [ "$readlock" == "Yes" ]; then
+   echo "Remove the $ctsm_python environment so we can install entirely from the conda-lock file"
    cmd="conda env remove --name $ctsm_python --quiet"
-   echo "$cmd"
    $cmd
    if [ $? != 0 ]; then
       echo "Trouble removing the $ctsm_python python environment which needs to be done before installing the lock file"
       exit -2
    fi
-   cmd="conda-lock install  --no-validate-platform --name $ctsm_python $condafilepath"
+   cmd="conda-lock install --log-level $loglevel --no-validate-platform --name $ctsm_python $condafilepath"
 else
    cmd="conda install --yes $verbosity --channel conda-forge --name $ctsm_python --file $condafilepath $option"
 fi
@@ -204,7 +229,6 @@ fi
 #
 echo "Installing the $condalockenv environment, so that you can use the --read-lock option later"
 cmd="conda install --yes $verbosity --mkdir --channel conda-forge --name $condalockenv --file $condadir/$condalockenvfile"
-echo "$cmd"
 $cmd
 if [ $? != 0 ]; then
    echo "Trouble installing the $condalockenv python environment"
@@ -225,10 +249,7 @@ echo "conda activate $ctsm_python"
 #
 if [ "$writelock" == "Yes" ]; then
    echo "Write the conda-lock as asked for by the --write-lock option"
-   loglevel="ERROR"
-   if [ "$verbose" == "Yes" ]; then
-       loglevel="INFO"
-   fi
+   # conda init bash may be required to activate the environemnt
    conda init bash
    conda activate $condalockenv
    if [ $? != 0 ]; then
@@ -244,4 +265,6 @@ if [ "$writelock" == "Yes" ]; then
    else
       echo "Successfully wrote out the lock file for $platform"
    fi
+   cmd="conda deactivate"
+   $cmd
 fi
