Many changes for testing py_env_create.

diff --git a/py_env_create b/py_env_create
--- a/py_env_create
+++ b/py_env_create
@@ -8,11 +8,8 @@
 set -e
 trap 'echo "Exiting on Ctrl+C"; exit 130' INT
 
-# For safety, do not allow running this while a conda environment is active
-if [[ $CONDA_PREFIX != "" ]]; then
-   echo "py_env_create must not be run within a conda environment. Try again after doing: conda deactivate" >&2
-   exit 1
-fi
+SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+cd "${SCRIPT_DIR}"
 
 dir=${0%/*}
 if [ "$dir" = "$0" ];then
@@ -39,7 +36,7 @@ new_env_name=ctsm_pylib
 condadir="$dir/python"
 
 domain=`domainname`
-condafile="conda_env_ctsm_py.txt"
+condafile="${condadir}/conda_env_ctsm_py.txt"
 #----------------------------------------------------------------------
 # Usage subroutine
 usage() {
@@ -59,6 +56,14 @@ usage() {
   echo "     Default is: $condafile"
   echo "[-n|--name <environment name>]  "
   echo "     Name of the environment you wish to create. Default: ${new_env_name}"
+  echo "[-t|--testing]  "
+  echo "     Install additional Python packages for testing py_env_create"
+  echo "[-o|--overwrite]  "
+  echo "     Overwrite existing conda env with same name, if any"
+  echo "[-r|--rename-existing] <name>  "
+  echo "     Rename existing conda env with same name, if any"
+  echo "[-y|--yes]  "
+  echo "     Do not ask for confirmation"
   echo "[--option <option>]  "
   echo "     Option(s) to pass to 'conda install' step"
   echo "***********************************************************************"
@@ -66,6 +71,10 @@ usage() {
 
 verbose="No"
 option=""
+testing_packages=0
+yes=""
+new_name_for_existing=""
+overwrite=0
 while [ $# -gt 0 ]; do
    case $1 in
        -h|--help )
@@ -83,9 +92,22 @@ while [ $# -gt 0 ]; do
            new_env_name=$2
            shift
            ;;
+       -o|--overwrite )
+           overwrite=1
+           ;;
        --option )
            option=$2
            shift
+           ;;
+       -r|--rename-existing )
+           new_name_for_existing=$2
+           shift
+           ;;
+       -t|--testing )
+           testing_packages=1
+           ;;
+       -y|--yes )
+           yes="--yes"
            ;;
        * )
            echo "ERROR:: invalid argument sent in: $2"
@@ -99,33 +121,65 @@ done
 #
 # Error checking options and setup
 #
-if [ ! -f $condadir/$condafile ]; then
-   echo "$condadir/$condafile does NOT exist"
+if [ ! -f $condafile ]; then
+   echo "$condafile does NOT exist"
    echo "Use the --file option with a valid filename"
    exit -1
 fi
+if [[ ${testing_packages} -eq 1 ]]; then
+   testing_packages_condafile="python/python_packages_for_testing_py_env_create.txt"
+   if [[ ! -f "${testing_packages_condafile}" ]]; then
+      echo "File not found: ${testing_packages_condafile}" >&2
+      exit 1
+   fi
+   new_condafile="${condafile}.testing_packages.$(date "+%Y%m%d%H%M%S%N")"
+   cat "${condafile}" > "${new_condafile}"
+   cat "${testing_packages_condafile}" >> "${new_condafile}"
+   condafile="${new_condafile}"
+fi
 
 echo "Use conda to install the python environment needed to run the CTSM python tools in the conda environment: $new_env_name"
-echo "Using the file: $condadir/$condafile"
+echo "Using the file: $condafile"
 
 #
 # Ask the user how to handle an environment that already exists
 #
 function conda_env_exists {
-   conda env list | grep -oE "^$1\s" | wc -l
+   conda env list | grep -oE "/$1$" | wc -l
 }
 function rename_existing_env {
-   if [[ $(conda_env_exists ${renamed_existing}) -eq 0 ]]; then
+   if [[ "$CONDA_DEFAULT_ENV" == *"$1" ]]; then
+      echo "Not going to let you rename the currently active conda env"
+      exit 1
+   elif [[ $(conda_env_exists $2) -eq 0 ]]; then
       echo "Renaming $1 to $2 (this will take a few minutes)..."
-      conda rename -n $1 $2 1>/dev/null  # -q/--quiet option not available on Derecho
+      conda rename ${yes} -n $1 $2 1>/dev/null  # -q/--quiet option not available on Derecho
    else
-      echo "${renamed_existing} also already exists"
+      echo "$2 also already exists"
    fi
 }
+function overwrite_existing_env {
+   if [[ "$CONDA_DEFAULT_ENV" == *"$1" ]]; then
+      echo "Not going to let you overwrite the currently active conda env"
+      exit 1
+   else
+      conda remove ${yes} -n $1 --all --quiet
+   fi
+}
+
 while [[ $(conda_env_exists ${new_env_name}) -gt 0 ]]; do
+
+   if [[ "${new_name_for_existing}" != "" ]]; then
+      rename_existing_env ${new_env_name} ${new_name_for_existing}
+      break
+   elif [[ ${overwrite} -eq 1 ]]; then
+      overwrite_existing_env ${new_env_name}
+      break
+   fi
+
    read -p "Conda environment '${new_env_name}' already exists. [o]verwrite, change [e]xisting env name, change [n]ew env name, or [c]ancel? " answer
    case $answer in
-      [Oo]* ) conda remove -n ${new_env_name} --all --quiet; break;;
+      [Oo]* ) overwrite_existing_env ${new_env_name}; break;;
       [Ee]* ) read -p "New name for existing conda env: " renamed_existing; rename_existing_env ${new_env_name} ${renamed_existing} ;;
       [Nn]* ) read -p "New name for conda env we're creating: " new_env_name;;
       [Cc]* ) exit;;
@@ -137,12 +191,12 @@ done
 # Create the environment
 #
 echo "Create $new_env_name"
-cmd="conda create --force --name $new_env_name --quiet"
+cmd="conda create ${yes} --name $new_env_name --quiet"
 echo "$cmd"
 $cmd
 
 #
-# Install the environemnt
+# Install the environment
 #
 echo "Installing $new_env_name; this can take a few minutes."
 echo "    ...."
@@ -154,7 +208,7 @@ if [ "$verbose" == "Yes" ]; then
   verbosity="--verbose"
   loglevel="INFO"
 fi
-cmd="conda install --yes $verbosity --channel conda-forge --name $new_env_name --file $condadir/$condafile $option"
+cmd="conda install ${yes} $verbosity --channel conda-forge --name $new_env_name --file $condafile $option"
 echo "$cmd"
 set +e
 $cmd
@@ -162,7 +216,7 @@ result=$?
 set -e
 if [ $result != 0 ]; then
    echo "Trouble installing the $new_env_name python environment"
-   echo "There must be a problem in the $condadir/$condafile conda specification environment file"
+   echo "There must be a problem in the $condafile conda specification environment file"
    echo "Change the file and try again"
    exit -2
 fi
@@ -173,3 +227,10 @@ echo "Successfully installed the $new_env_name python environment"
 echo
 echo "activate the environment by doing the following..."
 echo "conda activate $new_env_name"
+
+#
+# Delete tmp file
+#
+if [[ ${testing_packages} -eq 1 ]]; then
+   rm "${new_condafile}"
+fi
