Error in Hillslope/shell_commands if running on grid w/o a hillslope_file.

diff --git a/cime_config/testdefs/testmods_dirs/clm/Hillslope/shell_commands b/cime_config/testdefs/testmods_dirs/clm/Hillslope/shell_commands
--- a/cime_config/testdefs/testmods_dirs/clm/Hillslope/shell_commands
+++ b/cime_config/testdefs/testmods_dirs/clm/Hillslope/shell_commands
@@ -1,5 +1,17 @@
 ./xmlchange CLM_BLDNML_OPTS="-bgc sp"
 DIN_LOC_ROOT=$(./xmlquery --value DIN_LOC_ROOT)
+
+# Set hillslope_file. Needed for any grids without default hillslope_file already set by CTSM.
+lnd_grid=$(./xmlquery --value LND_GRID)
+if [[ ${lnd_grid} == "10x15" ]]; then
+    hillslope_file='$DIN_LOC_ROOT/lnd/clm2/testdata/synthetic_cosphill_1.3.nc'
+else
+    echo "ERROR: Hillslope file not found for LND_GRID=${lnd_grid}" >&2
+    exit 1
+fi
+echo -e "hillslope_file = '${hillslope_file}'\n" >> user_nl_clm
+
+# Set mesh file
 meshfile=$DIN_LOC_ROOT/lnd/clm2/testdata/ESMFmesh_10x15_synthetic_cosphill_1.0.nc
 ./xmlchange ATM_DOMAIN_MESH=${meshfile},LND_DOMAIN_MESH=${meshfile}
 
