clm4_0_41
Get working with latest scripts and have clm template call build-namelist directly.  Move
rmfmesh/rtmmap branch to trunk. Remove CASA completely. Start using RTM mapping files.
Allow bigger tolerance for mksurfdata_map frac up to 1.e-5 so can work for f4x5. New
half-degree mapping files. Remove code to calculate RTM mapping. Remove ability to set
maxpatch_pft to something different than numpft in CLM configure. Remove
-ad_spinup/-exit_spinup options in configure make generic -spinup option with a few
allowed values (similar to the clm45sci version of configure). New 1850 fsurdat dataset
for ne240np4. Update externals to the latest, get test_driver working.

Requirements for tag: test on bluefire (CESM,int,bat), lynx/pgi (CESM), mirage,
template calls build-namelist. Fix 1477, 1476, 1468, 1467

diff --git a/bld/clm.cpl7.template b/bld/clm.cpl7.template
--- a/bld/clm.cpl7.template
+++ b/bld/clm.cpl7.template
@@ -4,191 +4,191 @@ if !(-d $CASEBUILD) mkdir $CASEBUILD
 if !(-d $CASEBUILD/clmconf) mkdir $CASEBUILD/clmconf
 
 #--------------------------------------------------------------------
-# Invoke configure
+# Invoke cclm configure - output will go in CASEBUILD/clmconf
 #--------------------------------------------------------------------
-
-set cfgdir = $CASEBUILD/clmconf  
-set config = $cfgdir/config_cache.xml
-cd $cfgdir
 
 setenv COMP "unknown"
 if ($COMP_INTERFACE == 'MCT' ) setenv COMP mct
 if ($COMP_INTERFACE == 'ESMF') setenv COMP esmf
 
-set config_opts = "-mode ext_cesm "
-set config_opts = "$config_opts $CLM_CONFIG_OPTS"
+cd $CASEBUILD/clmconf  
 
-$CODEROOT/lnd/clm/bld/configure $config_opts \
-    -comp_intf cpl_\$COMP \
-    -clm_root \$CODEROOT/lnd/clm \
-    -usr_src \$CASEROOT/SourceMods/src.clm || exit -1 
-
-#--------------------------------------------------------------------
-# Invoke build-namelist
-#--------------------------------------------------------------------
-
-# RTM resolution (only R05 is available now)
-# R19 (19-basin) and RX1 do have RTM to Ocean mapping files available
-# BUT -- we don't have CLM datasets available for these resolutions
-setenv CLM_RTM_RES "R05"
-
-set finidat = " "
-if ($RUN_TYPE == hybrid) set finidat = " finidat = '${RUN_REFCASE}.clm2.r.${RUN_REFDATE}-${RUN_REFTOD}.nc' "
-set nrevsn = " "
-if ($RUN_TYPE == branch) set nrevsn   = " nrevsn = '${RUN_REFCASE}.clm2.r.${RUN_REFDATE}-${RUN_REFTOD}.nc' "
-
-@ clm_dtime  = ( 3600 * 24 ) / $LND_NCPL
-
-set rtm_tstep = " -rtm_tstep 10800 "             # RTM time-step every 3 hours
-set rtm_res   = " -rtm_res $CLM_RTM_RES"
-set co2ppmv   = " -co2_ppmv $CCSM_CO2_PPMV"
-set co2type   = " co2_type  =  '$CLM_CO2_TYPE'"
-
-cat >> $cfgdir/cesm_namelist << EOF1
- &clm_inparm
- dtime            =  $clm_dtime
- fatmlndfrc       =  '${LND_DOMAIN_PATH}/${LND_DOMAIN_FILE}'
-$co2type
-$finidat
-$nrevsn
-/
-EOF1
-
-# Allow the user to supply namelist values by putting them in the file
-# $CASEROOT/user_nl_clm.  The file should contain
-# a valid namelist.
-set USER_NL = "-infile cesm_namelist"
-if (-f "$CASEROOT/user_nl_clm" || -d "$CASEROOT/user_nl_clm" ) then
-   set USER_NL = "${USER_NL},$CASEROOT/user_nl_clm"
+set config_opts=" "
+if ($LND_GRID == "reg" && $GRID != "CLM_USRDAT" ) then
+   set config_opts=" -sitespf_pt $GRID"
 endif
 
-#
-# Other options to build-namelist
-#
-if ($RUN_TYPE == startup ) then
-   set START_TYPE = "default"
-   if ($CLM_FORCE_COLDSTART == on) set START_TYPE = "cold"
+$CODEROOT/lnd/clm/bld/configure  $config_opts \
+    -comp_intf cpl_\$COMP $CLM_CONFIG_OPTS -usr_src \$CASEROOT/SourceMods/src.clm || exit -1 
+
+#--------------------------------------------------------------------
+# Create clm.buildnml.csh
+#--------------------------------------------------------------------
+
+# copy necessary files to $CASEROOT/Tools/Templates/
+if ($NINST_LND > 1) then
+   set inst_counter = 1
+   set inst_string = ""
+   while ($inst_counter <= $NINST_LND)
+      set inst_string = $inst_counter
+      if ($inst_counter <= 999) setenv inst_string  "0$inst_string"
+      if ($inst_counter <=  99) setenv inst_string  "0$inst_string"
+      if ($inst_counter <=   9) setenv inst_string  "0$inst_string"
+      cp $CODEROOT/lnd/clm/bld/user_nl_clm $CASEROOT/user_nl_clm${inst_string}
+      @ inst_counter = $inst_counter + 1
+   end 
 else
-   set START_TYPE = $RUN_TYPE
-   if ($RUN_TYPE == hybrid ) set START_TYPE = "startup"
+   cp $CODEROOT/lnd/clm/bld/user_nl_clm $CASEROOT/user_nl_clm
 endif
 
-set mask = " "
-if ($ATM_GRID != $OCN_GRID) then
-   set mask = "-mask $OCN_GRID"
-endif
+# create clm.buildnml.csh
+cat >! $CASEBUILD/clm.buildnml.csh << EOF
+#! /bin/csh -f 
 
-set RESOLUTION = $LND_GRID
-if ($LND_GRID == reg ) then
-   if ( $GRID == CLM_USRDAT ) then
-      if ( ! $?CLM_USRDAT_NAME ) then
-         echo "ERROR: must set CLM_USRDAT_NAME xml variable if GRID is CLM_USRDAT"
+# Error check that CLM_USRDAT_NAME is set if CLM_USRDAT grid
+if (\$LND_GRID == reg ) then
+   if ( \$GRID == CLM_USRDAT ) then
+      if ( ! \$?CLM_USRDAT_NAME ) then
+         echo "clm.buildnml.csh ERROR: must set CLM_USRDAT_NAME xml variable if GRID is CLM_USRDAT"
          exit -1
-      else if ( ?CLM_USRDAT_NAME == UNSET ) then
-         echo "ERROR: must set CLM_USRDAT_NAME variable to a value other than UNSET "
-         echo "ERROR: for cases where GRID is CLM_USRDAT"
+      else if ( \$CLM_USRDAT_NAME == UNSET ) then
+         echo "clm.buildnml.csh ERROR: must set CLM_USRDAT_NAME variable to a value other than UNSET "
+         echo "clm.buildnml.csh ERROR: for cases where GRID is CLM_USRDAT"
          exit -1
       endif
-      set RESOLUTION = "$CLM_USRDAT_NAME"
-   else
-      set RESOLUTION = $GRID
    endif
 endif
 
-# following logic may need tweaking to account for configurations where start year is important
-if ($RUN_STARTDATE =~ *-01-01* || $RUN_STARTDATE =~ *-09-01*) then
-    set ignore = "-ignore_ic_year"
+# ---- set build-namelist flags ----
+
+if (\$RUN_TYPE == startup ) then
+   if ($CLM_FORCE_COLDSTART == on) then
+     set START_TYPE = "cold"
+   else
+     set START_TYPE = "default"
+   endif
 else
-    set ignore = "-ignore_ic_date"
+   if (\$RUN_TYPE == hybrid ) then
+     set START_TYPE = "startup"
+   else
+     set START_TYPE = \$RUN_TYPE
+   endif
 endif
 
-if ("$CLM_NML_USE_CASE" == "UNSET") then
-    set usecase = " "
-else
-    set usecase = "-use_case $CLM_NML_USE_CASE"
+set RESOLUTION = \$LND_GRID
+if (\$LND_GRID == reg ) then
+   if ( \$GRID == CLM_USRDAT ) then
+      set RESOLUTION = \$CLM_USRDAT_NAME
+   else
+      set RESOLUTION = \$GRID
+   endif
 endif
 
-# Global River Transport model off for single point mode
-if ($LND_GRID == reg || $PTS_MODE == TRUE ) then
+set usecase = " "
+if (\$CLM_NML_USE_CASE != "UNSET") then
+  set usecase = "-use_case \$CLM_NML_USE_CASE"
+endif
+
+set rtm = " "
+if (\$LND_GRID == reg || \$PTS_MODE == TRUE ) then
+   # Global River Transport model off for single point mode
    set rtm = "-rtm off"
-else
-   set rtm = " "
 endif
 
-set options    = ""
-if ( $CLM_USRDAT_NAME != UNSET ) then
-    set options = "-clm_usr_name $CLM_USRDAT_NAME"
+set ignore = "-ignore_ic_date"
+if (\$RUN_STARTDATE =~ *-01-01* || \$RUN_STARTDATE =~ *-09-01*) then
+  set ignore = "-ignore_ic_year"
 endif
-set options = "$options -config $CASEBUILD/clmconf/config_cache.xml -res $RESOLUTION $mask $ignore $usecase"
-set options = "$options $USER_NL -clm_start_type $START_TYPE"
-set options = "$options -glc_nec $GLC_NEC"
-set options = "$options $rtm $rtm_res $rtm_tstep $co2ppmv"
-if ("$COMP_ATM" == "datm" )then
-   set options = "$options  -datm_presaero $DATM_PRESAERO"
-else
-   set options = "$options  -datm_presaero prognostic"
+
+set mask = " "
+if (\$OCN_GRID == "reg") then
+   # Don't set mask in this case
+else if (\$ATM_GRID != \$OCN_GRID) then
+   set mask = "-mask $OCN_GRID"
 endif
-if ("$COMP_GLC" != "sglc" )then
-   set GLC_SMB = .$GLC_SMB. # for fortran logicals
-   set options = "$options -glc_grid $GLC_GRID -glc_smb $GLC_SMB"
+
+set clm_usr_name = ""
+if ( "\$CLM_USRDAT_NAME" != "UNSET" ) then
+    set clm_usr_name = "-clm_usr_name \$CLM_USRDAT_NAME"
 endif
-set options = "$options $CLM_BLDNML_OPTS"
 
-$CODEROOT/lnd/clm*/bld/build-namelist $options \
-    -namelist "&clm_inparm $CLM_NAMELIST_OPTS /" \
-    -csmdata \$DIN_LOC_ROOT \
-    -inputdata $CASEBUILD/clm.input_data_list || exit -1
+set glc_opts = ""
+if ("\$COMP_GLC" != "sglc" )then
+   set glc_opts = "-glc_grid \$GLC_GRID -glc_smb .\$GLC_SMB. "
+endif
 
-# ---------------------------------------------------------------------------
-#  Create clm.buildnml.csg
-# ---------------------------------------------------------------------------
+@ clm_dtime    = ( 3600 * 24 ) / \$LND_NCPL
+set fatmlndfrc = " fatmlndfrc='\${LND_DOMAIN_PATH}/\${LND_DOMAIN_FILE}' "
+set co2_type   = " co2_type='\$CLM_CO2_TYPE' "
 
-cat >! $CASEBUILD/clm.buildnml.csh << EOF1
-#! /bin/csh -f 
-
-#******************************************************************#
-#                  WARNING:                                        #
-# - If the user changes any input datasets - be sure to give it a  #
-#   unique filename. Do not duplicate any existing input files     #
-#******************************************************************#
-
-set exedir = \$RUNDIR; cd \$exedir
-
+cd \$CASEBUILD/clmconf || exit -1 
 set default_lnd_in_filename = "lnd_in"
 
-set lnd_inst_counter = 1
+set inst_counter = 1
+while (\$inst_counter <= \$NINST_LND)
 
-while (\$lnd_inst_counter <= \$NINST_LND)
+if (\$NINST_LND > 1) then
+   set inst_string = \$inst_counter
+   if (\$inst_counter <= 999) set inst_string = "0\$inst_string"
+   if (\$inst_counter <=  99) set inst_string = "0\$inst_string"
+   if (\$inst_counter <=   9) set inst_string = "0\$inst_string"
+   set inst_string = "_\${inst_string}"    
+else
+   set inst_string = ""       
+endif
+set lnd_in_filename = \${default_lnd_in_filename}\${inst_string}
+set finidat = " "
+if (\$RUN_TYPE == hybrid) then
+   set finidat = " finidat='\${RUN_REFCASE}.clm2\${inst_string}.r.\${RUN_REFDATE}-\${RUN_REFTOD}.nc' "
+endif
+set nrevsn  = " "
+if (\$RUN_TYPE == branch) then
+  set nrevsn   = "  nrevsn='\${RUN_REFCASE}.clm2\${inst_string}.r.\${RUN_REFDATE}-\${RUN_REFTOD}.nc' "
+endif
 
-    set lnd_in_filename = \$default_lnd_in_filename
-
-    if (\$NINST_LND > 1) then
-        set lnd_inst_string = \$lnd_inst_counter
-        if (\$lnd_inst_counter <= 999) set lnd_inst_string = 0\$lnd_inst_string
-        if (\$lnd_inst_counter <=  99) set lnd_inst_string = 0\$lnd_inst_string
-        if (\$lnd_inst_counter <=   9) set lnd_inst_string = 0\$lnd_inst_string
-        set lnd_in_filename = \${default_lnd_in_filename}_\${lnd_inst_string}
-    endif
-
-    cat >! \$lnd_in_filename << EOF
-
+cat >! \$CASEBUILD/clmconf/cesm_namelist << EOF1
+&clm_inparm
+ dtime = \$clm_dtime
+ \$fatmlndfrc 
+ \$co2_type
+ \$finidat
+ \$nrevsn
+EOF1
+if (-e \$CASEROOT/user_nl_clm\${inst_string}) then
+  \$UTILROOT/Tools/user_nl_add -user_nl_file \$CASEROOT/user_nl_clm\${inst_string} >> \$CASEBUILD/clmconf/cesm_namelist 
+endif
+cat >> \$CASEBUILD/clmconf/cesm_namelist << EOF1
+/
 EOF1
 
-    cat lnd_in >> $CASEBUILD/clm.buildnml.csh || exit -1
-cat >> $CASEBUILD/clm.buildnml.csh << EOF1
-EOF
+if (-e \$CASEBUILD/clm.input_data_list) then
+  rm \$CASEBUILD/clm.input_data_list
+endif
 
-    @ lnd_inst_counter = \$lnd_inst_counter + 1
+\$CODEROOT/lnd/clm/bld/build-namelist -infile \$CASEBUILD/clmconf/cesm_namelist \
+    -csmdata \$DIN_LOC_ROOT  \
+    -inputdata \$CASEBUILD/clm.input_data_list \
+    -namelist "&clm_inparm \$CLM_NAMELIST_OPTS /" \
+     \$ignore \$usecase \$clm_usr_name \$glc_opts \
+    -res \$RESOLUTION \$mask \
+    -clm_start_type \$START_TYPE \
+    -rtm_tstep 10800 \
+    -co2_ppmv \$CCSM_CO2_PPMV \
+    \$rtm  -glc_nec \$GLC_NEC \
+    -config \$CASEBUILD/clmconf/config_cache.xml \$CLM_BLDNML_OPTS
+    
+if (\$?DOCDIR) then # only set in preview_namelists utility		    
+  cp \$CASEBUILD/clmconf/lnd_in \$CASEROOT/CaseDocs/\$lnd_in_filename || exit -1
+endif
+if (-d \${RUNDIR}) then
+  cp \$CASEBUILD/clmconf/lnd_in \${RUNDIR}/\$lnd_in_filename || exit -2
+endif
+
+@ inst_counter = \$inst_counter + 1
 
 end
 
-EOF1
-
-#
-# Remove temporary namelist in the clmconf directory
-# (Leave config_cache.xml file as it documents what was done here)
-#
-\rm -f $CASEBUILD/clmconf/lnd_in* $CASEBUILD/clmconf/cesm_namelist
+EOF
 
 #--------------------------------------------------------------------
 # Create clm.buildexe.csh
@@ -197,36 +197,25 @@ EOF1
 cat >! $CASEBUILD/clm.buildexe.csh << EOF2
 #! /bin/csh -f 
 
-set objdir = \$OBJROOT/lnd/obj; cd \$objdir
-
-#--------------------------------------------------------------------
-# check basic task and thread settings
-#--------------------------------------------------------------------
-
-cp -f \$CASEBUILD/clmconf/CESM_cppdefs .tmp
-cmp -s .tmp CESM_cppdefs || mv -f .tmp CESM_cppdefs
+cd \$OBJROOT/lnd/obj
 
 setenv COMP "unknown"
 if (\$COMP_INTERFACE == 'MCT' ) setenv COMP mct
 if (\$COMP_INTERFACE == 'ESMF') setenv COMP esmf
 
-\cat >! .tmp << EOF; cmp -s .tmp Filepath || mv -f .tmp Filepath
+\cat >! .tmp << EOF; cmp -s .tmp Filepath || mv -f .tmp Filepath 
 EOF2
+
 cat $CASEBUILD/clmconf/Filepath >> $CASEBUILD/clm.buildexe.csh
+
 cat >> $CASEBUILD/clm.buildexe.csh << EOF2
 EOF
 
-#
-# Build the clm library
-#
 set clmdefs = "`cat \$CASEBUILD/clmconf/CESM_cppdefs`"
 if ( ! \$?GMAKE ) setenv GMAKE gmake
-\$GMAKE complib -j \$GMAKE_J MODEL=clm COMPLIB=\$LIBROOT/liblnd.a MACFILE=\$CASEROOT/Macros.\$MACH USER_CPPDEFS="\$clmdefs" -f \$CASETOOLS/Makefile || exit 2
+\$GMAKE complib -j \$GMAKE_J MODEL=clm COMPLIB=\$LIBROOT/liblnd.a USER_CPPDEFS="\$clmdefs" -f \$CASETOOLS/Makefile || exit 2
+
+wait
 
 EOF2
 
-#
-# Remove any temporary configure files in the clmconf directory
-# (Some files are still used in clm.buildexe.csh, so leave those around: CESM_cppdefs)
-#
-\rm -f $CASEBUILD/clmconf/Filepath
