clm3_6_07
New build version.

diff --git a/bld/clm.cpl7.template b/bld/clm.cpl7.template
--- a/bld/clm.cpl7.template
+++ b/bld/clm.cpl7.template
@@ -4,6 +4,16 @@ if !(-d $CASEROOT/Buildnml_Prestage) mkdir $CASEROOT/Buildnml_Prestage
 if !(-d $CASEROOT/Buildnml_Prestage/clmconf) mkdir $CASEROOT/Buildnml_Prestage/clmconf
 if !(-d $CASEROOT/Buildexe) mkdir $CASEROOT/Buildexe
 
+#--------------------------------------------------------------------
+# Configure clm and create resolved namelist script
+#--------------------------------------------------------------------
+
+#--- if CLM is expecting co2 from coupler, then must turn on the co2 interfaces ---   
+if ( "$CLM_CO2_TYPE" != constant && "$CCSM_BGC" == none) then  
+   echo "clm error: CLM_CO2_TYPE is not constant, must set CCSM_BGC to other than none"
+   exit 3
+endif
+
 # --- set hybrid run initial dataset 
 set datainit = " "
 if ($RUN_TYPE == hybrid) set datainit = ${RUN_REFCASE}.clm2.r.${RUN_REFDATE}-00000.nc 
@@ -12,51 +22,43 @@ if ($RUN_TYPE == hybrid) set datainit = ${RUN_REFCASE}.clm2.r.${RUN_REFDATE}-000
 set nrevsn = " "
 if ($RUN_TYPE == branch) set nrevsn   = ${RUN_REFCASE}.clm2.r.${RUN_REFDATE}-00000.nc 
 
-# --- set basedate_num - used for branch or hybrid runs 
-set basedate_num = `echo $RUN_STARTDATE | sed -e 's/-//g'`  # remove "-"
+set targetos=" "
+#if ($OS == 'UNICOS') then
+#   set targetos="-target_os unicosmp"
+#endif
 
-#
-# Configure clm
-#--------------------------------------------------------------------
 if ( $CLM_BGC == CN )then
-  set bgc="cn"
-  set pft=numpft+1
+  set bgc = '-bgc cn'
+  set maxpft = '-maxpft numpft+1'
 else if ( $CLM_BGC == CASA )then
-  set bgc="casa"
-  set pft=4
+  set bgc = '-bgc casa'
+  set maxpft = '-maxpft 4'
 else
-  set bgc="none"
-  set pft=4
-endif
-if ($OS == 'UNICOS') then
-   set targetos="-target_os unicosmp"
-else
-   set targetos=" "
+  set bgc = '-bgc none'
+  set maxpft = '-maxpft 4'
 endif
 
-set cfgdir = $CASEROOT/Buildnml_Prestage/clmconf
-cd $cfgdir
-$CODEROOT/lnd/clm*/bld/configure -s -spmd -mode ext_ccsm_seq -rtm on -bgc $bgc -maxpft $pft -clm_bld $cfgdir \
-                                  $targetos -usr_src $CASEROOT/SourceMods/src.clm
+set sim_year = '-sim_year 2000'
+if ($CCSM_IPCC == 1870_control       ) set sim_year = '-sim_year 1890'
+if ($CCSM_IPCC == 2000_control       ) set sim_year = '-sim_year 2000'
+if ($CCSM_IPCC == OFF                ) set sim_year = '-sim_year 2000'
+if ($CCSM_IPCC == "1870-2000_control") set sim_year = ' '
 
-# ---------------------------------------------------------------------------
-#  Create resolved namelist and prestage data script
-# ---------------------------------------------------------------------------
 
 set config = $CASEROOT/Buildnml_Prestage/clmconf/config_cache.xml
-
-set sim_year = 2000
-if ($CCSM_IPCC == 1870_control       ) set sim_year=1890
-if ($CCSM_IPCC == 2000_control       ) set sim_year=2000
-if ($CCSM_IPCC == OFF                ) set sim_year=2000
-if ($CCSM_IPCC == "1870-2000_control") set sim_year=9999
 
 if ($CCSM_IPCC == "1870-2000_control") then
   setenv CLM_DYNNDEP "transient"
 endif
 
-#set options = "-config $config -justvalue -ccsm -silent "
- set options = "-config $config -justvalue -silent -csmdata $DIN_LOC_ROOT"
+if (     $CLM_DYNNDEP == "transient" && $CLM_BGC == "CN" ) set clm_demand = "-clm_demand fndepdyn"
+if (     $CLM_DYNPFT  == "transient" && $?clm_demand )then
+    set clm_demand = "$clm_demand,fpftdyn"
+else if ($CLM_DYNPFT  == "transient" )then
+    set clm_demand = '-clm_demand fpftdyn'
+else
+    set clm_demand = " "
+endif
 
 set res = $LND_GRID
 
@@ -65,106 +67,47 @@ if ($ATM_GRID == $OCN_GRID) then
    if ($ATM_GRID == 1.9x2.5 || $ATM_GRID == 0.9x1.25 || $ATM_GRID == 0.47x0.63 || $ATM_GRID == 0.23x0.31 ) \
       set mask = gx1v5
 else
-  set mask = "$OCN_GRID"
+  set mask = $OCN_GRID
 endif
-set options = "$options -res $res -options mask=$mask,sim_year=$sim_year"
+set mask = "-mask $mask"
 
-if ($CLM_ARB_IC == off )then
-   set finidat    = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl $options -demand -var finidat`
-   if ( $status != 0 ) exit 1
+set cfgdir = $CASEROOT/Buildnml_Prestage/clmconf  
+set config = $cfgdir/config_cache.xml
+cd $cfgdir
+
+cat >> $cfgdir/ccsm_namelist << EOF1
+ &clm_inparm
+ dtime            =  $CLM_DTIME
+ rtm_nsteps       =  $RTM_NSTEPS
+ nrevsn           = '$nrevsn'
+ hist_mfilt       =  1
+ hist_nhtfrq      =  0
+ hist_crtinic     = 'NONE'
+ co2_ppmv         =  $CCSM_CO2_PPMV
+ co2_type         = '$CLM_CO2_TYPE'
+EOF1
+
+$CODEROOT/lnd/clm*/bld/configure -verbose -spmd -mode ext_ccsm_seq -rtm on $bgc $maxpft -clm_bld $cfgdir \
+         $targetos -usr_src $CASEROOT/SourceMods/src.clm || exit -1 
+
+if ($RUN_TYPE == startup && $CLM_ARB_IC != off) then
+   set RUNTYPE = "arb_ic"
 else
-   set finidat    = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl $options         -var finidat`
-   if ( $status != 0   ) exit 1
-   if ( $finidat == "" ) set finidat = " "
-endif
-set pftdat     = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl    $options -demand -var fpftcon`
-if ( $status != 0 ) exit 1
-
-set rdirdat    = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl    $options -demand -var frivinp_rtm`
-if ( $status != 0 ) exit 1
-
-set fsurdat    = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl    $options -demand -var fsurdat`
-if ( $status != 0 ) exit 1
-
-set fatmgrid   = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl    $options -demand -var fatmgrid`
-if ( $status != 0 ) exit 1
-
-set fatmlndfrc = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl    $options -demand -var fatmlndfrc`
-if ( $status != 0 ) exit 1
-
-set fndepdyn   = " "
-set fndepdat   = " "
-if ($CLM_BGC == CN && $CLM_DYNNDEP == "transient") then
-   set fndepdyn = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl $options -demand -var fndepdyn`
-   if ( $status != 0 ) exit 1
-else if ($CLM_BGC == CN )then
-   set fndepdat = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl $options -demand -var fndepdat`
-   if ( $status != 0 ) exit 1
+   set RUNTYPE = $RUN_TYPE
 endif
 
-set fpftdyn    = " "
-if ($CLM_DYNPFT  == "transient") then
-   set fpftdyn = `$CODEROOT/lnd/clm*/bld/queryDefaultNamelist.pl  $options -demand -var fpftdyn`
-   if ( $status != 0 ) exit 1
-endif
-
-#---------------------------- begin build-namelist version ------------------------------------------------------
-#
-# Build-namelist version (requires at least branch_tags/bstrms_tags/bstrms1_clm3_5_11/ or later)
-#
-#cat >! lndinput << EOF
-# &drv_in
-# start_ymd        =  $basedate_num
-# start_tod        =  0
-# brnch_retain_casename = .false.
-# ctitle           = '$CASE $CASESTR'  
-# /
-# &clm_inparm
-# rtm_nsteps       =  $RTM_NSTEPS
-# dtime            =  $CLM_DTIME
-# irad             =  $iradsw
-# hist_nhtfrq      =  0
-# hist_crtinic     = 'NONE'
-# nrevsn           = '$nrevsn'
-# finidat          = '$finidat'
-# fsurdat          = '$fsurdat'
-# fatmgrid         = '$fatmgrid'
-# fatmlndfrc       = '$fatmlndfrc'
-# fpftcon          = '$pftdat'
-# fpftdyn          = '$fpftdyn'
-# frivinp_rtm      = '$rdirdat'
-# co2_type         = '$CLM_CO2_TYPE'
-# co2_ppmv         =  $CCSM_CO2_PPMV
-# fndepdat         = '$fndepdat'
-# fndepdyn         = '$fndepdyn'
-# /
-#EOF
-#if ( $OS == ESOS ) then
-#  cat lndinput | sed 's#^ */ *\$# clump_pproc      = 1#' >! lndinput.tmp
-#  echo ' /' >>! lndinput.tmp
-#  /bin/mv -f lndinput.tmp lndinput
-#endif
-#
-#if ($RUN_TYPE == startup && $CLM_ARB_IC != off) then
-#   set RUNTYPE = "arb_ic"
-#else
-#   set RUNTYPE = $RUN_TYPE
-#endif
-#set bnflags="-case $CASE -start_type $RUNTYPE -config $config -mask $mask"
-#set bnflags="$bnflags -sim_year $sim_year -infile lndinput -runlength 9999d"
-#$CODEROOT/lnd/clm*/bld/build-namelist $bnflags || exit -1
-#cat lnd.stdin
-#------------------------------ end build-namelist version ------------------------------------------------------
- 
-cat >! $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
-#! /bin/csh -f 
+set options = "-config $config -res $LND_GRID $mask $sim_year $clm_demand "
+set options = "$options -infile ccsm_namelist -start_type $RUNTYPE -case $CASE "
+$CODEROOT/lnd/clm*/bld/build-namelist $options -csmdata \$DIN_LOC_ROOT || exit -1
 
 # ---------------------------------------------------------------------------
 #  Create namelist and prestage data script
 # ---------------------------------------------------------------------------
 
-# Prestage data
-#--------------------------------------------------------------------
+cat >! $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
+#! /bin/csh -f 
+
+set exedir = \$EXEROOT/ccsm_se; cd \$exedir
 
 #******************************************************************#
 # If the user changes any input datasets - be sure to give it a    #
@@ -173,47 +116,17 @@ cat >! $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
 
 #******************************************************************#
 #                  WARNING:                                        #
-# CAM namelist variable dtime must have same value as              #
-# CLM namelist variable dtime                                      #
-# CAM namelist variable iradsw must have same value as             #
-# CLM namelist variable irad                                       #
+# CLM namelist variable dtime must have same value as              #
+# CAM namelist variable dtime                                      #
 #******************************************************************#
 
-# started as a $RUN_TYPE run
-
-set runtype = $RUN_TYPE
-if (\$CONTINUE_RUN == 'TRUE') set runtype = 'continue'
-
-set exedir = \$EXEROOT/ccsm_se; cd \$exedir
-
-set finidat    = "$finidat" 
-set nrevsn     = "$nrevsn"
-set pftdat     = "$pftdat"
-set rdirdat    = "$rdirdat"
-set fsurdat    = "$fsurdat"
-set fatmgrid   = "$fatmgrid"
-set fatmlndfrc = "$fatmlndfrc"
-set fndepdyn   = "$fndepdyn"
-set fndepdat   = "$fndepdat"
-set fpftdyn    = "$fpftdyn"
-
 EOF1
-
-if ($RUN_TYPE == 'startup') then
-cat >> $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
-if (\$PRESTAGE_DATA == TRUE) then
-if ( "\$finidat" != " " && "\$runtype" != continue) then
-   \$UTILROOT/Tools/ccsm_getinput \$finidat || exit 1 
-endif
-endif
-EOF1
-endif
 
 if ($RUN_TYPE == 'hybrid') then
 cat >> $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
 if ( "\$runtype" != continue) then
-   set finidat = "$datainit"
-   #\$UTILROOT/Tools/ccsm_getfile $RUN_REFCASE/lnd/init/\$finidat || exit 1 
+set datainit = $datainit
+#\$UTILROOT/Tools/ccsm_getfile $RUN_REFCASE/lnd/init/\$datainit || exit 1 
 endif
 EOF1
 endif
@@ -221,62 +134,18 @@ endif
 if ($RUN_TYPE == 'branch') then
 cat >> $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
 if ( "\$runtype" != 'continue') then
-  #\$UTILROOT/Tools/ccsm_getfile $RUN_REFCASE/lnd/rest/\$nrevsn || exit 1
+#\$UTILROOT/Tools/ccsm_getfile $RUN_REFCASE/lnd/rest/\$nrevsn || exit 1
 endif
 EOF1
 endif
 
 cat >> $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
-if (\$PRESTAGE_DATA == TRUE) then
-  \$UTILROOT/Tools/ccsm_getinput \$pftdat      || exit 1
-  \$UTILROOT/Tools/ccsm_getinput \$rdirdat     || exit 1
-  \$UTILROOT/Tools/ccsm_getinput \$fsurdat     || exit 1
-  \$UTILROOT/Tools/ccsm_getinput \$fatmgrid    || exit 1
-  \$UTILROOT/Tools/ccsm_getinput \$fatmlndfrc  || exit 1
-  if ( "\$fndepdyn" != " ") then
-    \$UTILROOT/Tools/ccsm_getinput \$fndepdyn  || exit 1
-  endif
-  if ( "\$fndepdat" != " ") then
-    \$UTILROOT/Tools/ccsm_getinput \$fndepdat  || exit 1
-  endif
-  if ( "\$fpftdyn" != " ") then
-    \$UTILROOT/Tools/ccsm_getinput \$fpftdyn   || exit 1
-  endif
-endif
-
-EOF1
-
-#--- if CLM is expecting co2 from coupler, then must turn on the co2 interfaces ---   
-if ( "$CLM_CO2_TYPE" != constant && "$CCSM_BGC" == none) then  
-   echo "atm error: CLM_CO2_TYPE is not constant, must set CCSM_BGC to other than none"
-   exit 3
-endif
-
-cat >> $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
-# Create resolved namelist
-#--------------------------------------------------------------------
 cat >! lnd_in << EOF
- &clm_inparm
- finidat          = '\$finidat'
- fsurdat          = '\$fsurdat'
- fatmgrid         = '\$fatmgrid'
- fatmlndfrc       = '\$fatmlndfrc'
- fpftcon          = '\$pftdat'
- fpftdyn          = '\$fpftdyn'
- frivinp_rtm      = '\$rdirdat'
- fndepdat         = '\$fndepdat'
- fndepdyn         = '\$fndepdyn'
- co2_type         = '$CLM_CO2_TYPE'
- co2_ppmv         =  $CCSM_CO2_PPMV
- dtime            =  $CLM_DTIME
- irad             =  $iradsw
- rtm_nsteps       =  $RTM_NSTEPS
- hist_nhtfrq      =  0
- hist_crtinic     = 'NONE'
- nrevsn           = '\$nrevsn'
- /
+EOF1
+cat lnd_in >> $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh || exit -1
+cat >> $CASEROOT/Buildnml_Prestage/clm.buildnml_prestage.csh << EOF1
+
 EOF
- 
 EOF1
 
 #--------------------------------------------------------------------
@@ -285,9 +154,6 @@ EOF1
 
 cat >! $CASEROOT/Buildexe/clm.buildexe.csh << EOF2
 #! /bin/csh -f 
-
-# Use namelist filename instead of redirecting from stdin
-echo "Use NLFILE rather than stdin for CLM"
 
 set exedir = \$EXEROOT/ccsm_se
 set objdir = \$OBJROOT/lnd/obj; cd \$objdir
@@ -326,9 +192,9 @@ if (\$BLDTYPE == 'TRUE') then
    cp \$BLDROOT/mkSrcfiles . || exit 2
    set THREAD = FALSE ;  if (\$NTHRDS_LND > 1) set THREAD = TRUE
    set clmdefs = "`cat \$CASEROOT/Buildnml_Prestage/clmconf/CCSM_cppdefs`"
-   gmake complib -j \$GMAKE_J CLM_CPPDEFS="\$clmdefs" MODEL=clm DEPINC=$INCROOT COMPLIB=\$objdir/../libclm.a \
+   gmake complib -j \$GMAKE_J CLM_CPPDEFS="\$clmdefs" MODEL=clm DEPINC=\$INCROOT COMPLIB=\$objdir/../libclm.a \
        VPFILE=Filepath THREAD=\$THREAD -f  \$BLDROOT/Makefile MACFILE=\$CASEROOT/Macros.\$MACH  || exit 2
-   cp -p *comp_*.mod $LIBROOT/include/
+   cp -p *comp_*.mod \$LIBROOT/include/
 endif
 
 if !(-f \$objdir/../libclm.a) then
