Pipe errors to stdout

diff --git a/cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands b/cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands
--- a/cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands
+++ b/cime_config/testdefs/testmods_dirs/clm/FatesSetupParamBuild/shell_commands
@@ -6,13 +6,13 @@
 check_error () {
    # Arguments: error, message
    if [ $# != 2 ]; then
-      echo "Wrong number of arguments to check_error"
+      echo "Wrong number of arguments to check_error" >&2
    fi
    error=$1
    msg=$2
    if [ $error != 0 ]; then
-      echo "ERROR: Command failed"
-      echo $msg
+      echo "ERROR: Command failed" >&2
+      echo $msg >&2
       exit 1
    fi
 }
@@ -42,7 +42,7 @@ fi
 which conda >& /dev/null
 error=$?
 if [ $error != 0 ]; then
-   echo "conda is NOT in your path and is used to get the python environment to run the FATES modify parameter file tool"
+   echo "conda is NOT in your path and is used to get the python environment to run the FATES modify parameter file tool" >&2
    noconda=1
 else
    if [ $DEBUG ]; then
@@ -55,7 +55,7 @@ fi
 
 MODIFY_FATES_PARAMFILE="$FATESDIR/tools/modify_fates_paramfile.py"
 if [ ! -f $MODIFY_FATES_PARAMFILE ]; then
-   echo "$MODIFY_FATES_PARAMFILE does NOT exist"
+   echo "$MODIFY_FATES_PARAMFILE does NOT exist" >&2
    exit 1
 elif [ $DEBUG ]; then
    echo "$MODIFY_FATES_PARAMFILE was found"
@@ -64,7 +64,7 @@ fi
 $MODIFY_FATES_PARAMFILE --help >& /dev/null
 error=$?
 if [ $error != 0 ]; then
-   echo "$MODIFY_FATES_PARAMFILE can NOT be successfully run"
+   echo "$MODIFY_FATES_PARAMFILE can NOT be successfully run" >&2
    if [ $noconda == 1 ]; then
       echo "Attempting to activate the conda ctsm_pylib environment"
       conda activate ctsm_pylib
@@ -73,11 +73,11 @@ if [ $error != 0 ]; then
          echo "conda activate ctsm_pylib was successful"
       fi
    else
-      echo "Make sure your python environment can run $MODIFY_FATES_PARAMFILE"
-      echo "One way to do that is to add conda to your environment"
-      echo "    then activate the ctsm_pylib environemnt"
-      echo "    in some cases you may have to add conda activate ctsm_pylib in your startup files"
-      echo "    ctsm_pylib is created at the top level of CTSM using py_env_create"
+      echo "Make sure your python environment can run $MODIFY_FATES_PARAMFILE" >&2
+      echo "One way to do that is to add conda to your environment" >&2
+      echo "    then activate the ctsm_pylib environemnt" >&2
+      echo "    in some cases you may have to add conda activate ctsm_pylib in your startup files" >&2
+      echo "    ctsm_pylib is created at the top level of CTSM using py_env_create" >&2
       exit 1
    fi
 elif [ $DEBUG ]; then
