lint_and_format.yml: Fix handling of failed pylint check.
Now a failed pylint check should actually be marked as failing.

diff --git a/.github/workflows/lint_and_format.yml b/.github/workflows/lint_and_format.yml
--- a/.github/workflows/lint_and_format.yml
+++ b/.github/workflows/lint_and_format.yml
@@ -33,13 +33,14 @@ jobs:
 
       # Run pylint check
       - name: Run pylint
-        continue-on-error: true
         run: |
           cd python
           conda run -n ctsm_pylib make lint
 
       # Run black check
       - name: Run black
+        # Run this step even if previous step(s) failed
+        if: success() || failure()
         run: |
           cd python
           conda run -n ctsm_pylib make black
