Move Python lint/black check into python-tests.yml.
Since they were working on the same triggers.

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -37,3 +37,31 @@ jobs:
         run: |
           cd python
           conda run -n ctsm_pylib ./run_ctsm_py_tests -u
+
+  python-lint-and-black:
+    runs-on: ubuntu-latest
+    steps:
+      # Checkout the code
+      - uses: actions/checkout@v4
+
+      # Set up the conda environment
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          activate-environment: ctsm_pylib
+          environment-file: python/conda_env_ctsm_py.yml
+          channels: conda-forge
+          auto-activate-base: false
+
+      # Run pylint check
+      - name: Run pylint
+        run: |
+          cd python
+          conda run -n ctsm_pylib make lint
+
+      # Run black check
+      - name: Run black
+        # Run this step even if previous step(s) failed
+        if: success() || failure()
+        run: |
+          cd python
+          conda run -n ctsm_pylib make black
